spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

server:
  port: 8080
  servlet:
    context-path: /mp